/**
 * @fileoverview gRPC-Web generated client stub for whitelabelairportrpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.0
// source: extension.proto

/* eslint-disable */
// @ts-nocheck

const grpc = {};
grpc.web = require("grpc-web");

var base_pb = require("./base_pb.js");
const proto = {};
proto.whitelabelairportrpc = require("./extension_pb.js");

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.whitelabelairportrpc.ExtensionHostServiceClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.whitelabelairportrpc.ExtensionHostServicePromiseClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.Empty,
 *   !proto.whitelabelairportrpc.ExtensionList>}
 */
const methodDescriptor_ExtensionHostService_ListExtensions =
  new grpc.web.MethodDescriptor(
    "/whitelabelairportrpc.ExtensionHostService/ListExtensions",
    grpc.web.MethodType.UNARY,
    base_pb.Empty,
    proto.whitelabelairportrpc.ExtensionList,
    /**
     * @param {!proto.whitelabelairportrpc.Empty} request
     * @return {!Uint8Array}
     */
    function (request) {
      return request.serializeBinary();
    },
    proto.whitelabelairportrpc.ExtensionList.deserializeBinary
  );

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.ExtensionList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.ExtensionList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.ExtensionHostServiceClient.prototype.listExtensions =
  function (request, metadata, callback) {
    return this.client_.rpcCall(
      this.hostname_ +
        "/whitelabelairportrpc.ExtensionHostService/ListExtensions",
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_ListExtensions,
      callback
    );
  };

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.ExtensionList>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.ExtensionHostServicePromiseClient.prototype.listExtensions =
  function (request, metadata) {
    return this.client_.unaryCall(
      this.hostname_ +
        "/whitelabelairportrpc.ExtensionHostService/ListExtensions",
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_ListExtensions
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.ExtensionRequest,
 *   !proto.whitelabelairportrpc.ExtensionResponse>}
 */
const methodDescriptor_ExtensionHostService_Connect =
  new grpc.web.MethodDescriptor(
    "/whitelabelairportrpc.ExtensionHostService/Connect",
    grpc.web.MethodType.SERVER_STREAMING,
    proto.whitelabelairportrpc.ExtensionRequest,
    proto.whitelabelairportrpc.ExtensionResponse,
    /**
     * @param {!proto.whitelabelairportrpc.ExtensionRequest} request
     * @return {!Uint8Array}
     */
    function (request) {
      return request.serializeBinary();
    },
    proto.whitelabelairportrpc.ExtensionResponse.deserializeBinary
  );

/**
 * @param {!proto.whitelabelairportrpc.ExtensionRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.ExtensionResponse>}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.ExtensionHostServiceClient.prototype.connect =
  function (request, metadata) {
    return this.client_.serverStreaming(
      this.hostname_ + "/whitelabelairportrpc.ExtensionHostService/Connect",
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_Connect
    );
  };

/**
 * @param {!proto.whitelabelairportrpc.ExtensionRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.ExtensionResponse>}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.ExtensionHostServicePromiseClient.prototype.connect =
  function (request, metadata) {
    return this.client_.serverStreaming(
      this.hostname_ + "/whitelabelairportrpc.ExtensionHostService/Connect",
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_Connect
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.EditExtensionRequest,
 *   !proto.whitelabelairportrpc.ExtensionActionResult>}
 */
const methodDescriptor_ExtensionHostService_EditExtension =
  new grpc.web.MethodDescriptor(
    "/whitelabelairportrpc.ExtensionHostService/EditExtension",
    grpc.web.MethodType.UNARY,
    proto.whitelabelairportrpc.EditExtensionRequest,
    proto.whitelabelairportrpc.ExtensionActionResult,
    /**
     * @param {!proto.whitelabelairportrpc.EditExtensionRequest} request
     * @return {!Uint8Array}
     */
    function (request) {
      return request.serializeBinary();
    },
    proto.whitelabelairportrpc.ExtensionActionResult.deserializeBinary
  );

/**
 * @param {!proto.whitelabelairportrpc.EditExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.ExtensionActionResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.ExtensionActionResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.ExtensionHostServiceClient.prototype.editExtension =
  function (request, metadata, callback) {
    return this.client_.rpcCall(
      this.hostname_ +
        "/whitelabelairportrpc.ExtensionHostService/EditExtension",
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_EditExtension,
      callback
    );
  };

/**
 * @param {!proto.whitelabelairportrpc.EditExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.ExtensionActionResult>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.ExtensionHostServicePromiseClient.prototype.editExtension =
  function (request, metadata) {
    return this.client_.unaryCall(
      this.hostname_ +
        "/whitelabelairportrpc.ExtensionHostService/EditExtension",
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_EditExtension
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.SendExtensionDataRequest,
 *   !proto.whitelabelairportrpc.ExtensionActionResult>}
 */
const methodDescriptor_ExtensionHostService_SubmitForm =
  new grpc.web.MethodDescriptor(
    "/whitelabelairportrpc.ExtensionHostService/SubmitForm",
    grpc.web.MethodType.UNARY,
    proto.whitelabelairportrpc.SendExtensionDataRequest,
    proto.whitelabelairportrpc.ExtensionActionResult,
    /**
     * @param {!proto.whitelabelairportrpc.SendExtensionDataRequest} request
     * @return {!Uint8Array}
     */
    function (request) {
      return request.serializeBinary();
    },
    proto.whitelabelairportrpc.ExtensionActionResult.deserializeBinary
  );

/**
 * @param {!proto.whitelabelairportrpc.SendExtensionDataRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.ExtensionActionResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.ExtensionActionResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.ExtensionHostServiceClient.prototype.submitForm =
  function (request, metadata, callback) {
    return this.client_.rpcCall(
      this.hostname_ + "/whitelabelairportrpc.ExtensionHostService/SubmitForm",
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_SubmitForm,
      callback
    );
  };

/**
 * @param {!proto.whitelabelairportrpc.SendExtensionDataRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.ExtensionActionResult>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.ExtensionHostServicePromiseClient.prototype.submitForm =
  function (request, metadata) {
    return this.client_.unaryCall(
      this.hostname_ + "/whitelabelairportrpc.ExtensionHostService/SubmitForm",
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_SubmitForm
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.ExtensionRequest,
 *   !proto.whitelabelairportrpc.ExtensionActionResult>}
 */
const methodDescriptor_ExtensionHostService_Close =
  new grpc.web.MethodDescriptor(
    "/whitelabelairportrpc.ExtensionHostService/Close",
    grpc.web.MethodType.UNARY,
    proto.whitelabelairportrpc.ExtensionRequest,
    proto.whitelabelairportrpc.ExtensionActionResult,
    /**
     * @param {!proto.whitelabelairportrpc.ExtensionRequest} request
     * @return {!Uint8Array}
     */
    function (request) {
      return request.serializeBinary();
    },
    proto.whitelabelairportrpc.ExtensionActionResult.deserializeBinary
  );

/**
 * @param {!proto.whitelabelairportrpc.ExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.ExtensionActionResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.ExtensionActionResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.ExtensionHostServiceClient.prototype.close =
  function (request, metadata, callback) {
    return this.client_.rpcCall(
      this.hostname_ + "/whitelabelairportrpc.ExtensionHostService/Close",
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_Close,
      callback
    );
  };

/**
 * @param {!proto.whitelabelairportrpc.ExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.ExtensionActionResult>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.ExtensionHostServicePromiseClient.prototype.close =
  function (request, metadata) {
    return this.client_.unaryCall(
      this.hostname_ + "/whitelabelairportrpc.ExtensionHostService/Close",
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_Close
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.ExtensionRequest,
 *   !proto.whitelabelairportrpc.ExtensionActionResult>}
 */
const methodDescriptor_ExtensionHostService_GetUI =
  new grpc.web.MethodDescriptor(
    "/whitelabelairportrpc.ExtensionHostService/GetUI",
    grpc.web.MethodType.UNARY,
    proto.whitelabelairportrpc.ExtensionRequest,
    proto.whitelabelairportrpc.ExtensionActionResult,
    /**
     * @param {!proto.whitelabelairportrpc.ExtensionRequest} request
     * @return {!Uint8Array}
     */
    function (request) {
      return request.serializeBinary();
    },
    proto.whitelabelairportrpc.ExtensionActionResult.deserializeBinary
  );

/**
 * @param {!proto.whitelabelairportrpc.ExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.ExtensionActionResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.ExtensionActionResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.ExtensionHostServiceClient.prototype.getUI =
  function (request, metadata, callback) {
    return this.client_.rpcCall(
      this.hostname_ + "/whitelabelairportrpc.ExtensionHostService/GetUI",
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_GetUI,
      callback
    );
  };

/**
 * @param {!proto.whitelabelairportrpc.ExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.ExtensionActionResult>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.ExtensionHostServicePromiseClient.prototype.getUI =
  function (request, metadata) {
    return this.client_.unaryCall(
      this.hostname_ + "/whitelabelairportrpc.ExtensionHostService/GetUI",
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_GetUI
    );
  };

module.exports = proto.whitelabelairportrpc;
