// source: extension.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require("google-protobuf");
var goog = jspb;
var global =
  (typeof globalThis !== "undefined" && globalThis) ||
  (typeof window !== "undefined" && window) ||
  (typeof global !== "undefined" && global) ||
  (typeof self !== "undefined" && self) ||
  function () {
    return this;
  }.call(null) ||
  Function("return this")();

var base_pb = require("./base_pb.js");
goog.object.extend(proto, base_pb);
goog.exportSymbol(
  "proto.whitelabelairportrpc.EditExtensionRequest",
  null,
  global
);
goog.exportSymbol("proto.whitelabelairportrpc.Extension", null, global);
goog.exportSymbol(
  "proto.whitelabelairportrpc.ExtensionActionResult",
  null,
  global
);
goog.exportSymbol("proto.whitelabelairportrpc.ExtensionList", null, global);
goog.exportSymbol("proto.whitelabelairportrpc.ExtensionRequest", null, global);
goog.exportSymbol("proto.whitelabelairportrpc.ExtensionResponse", null, global);
goog.exportSymbol(
  "proto.whitelabelairportrpc.ExtensionResponseType",
  null,
  global
);
goog.exportSymbol(
  "proto.whitelabelairportrpc.SendExtensionDataRequest",
  null,
  global
);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.whitelabelairportrpc.ExtensionActionResult = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.whitelabelairportrpc.ExtensionActionResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.whitelabelairportrpc.ExtensionActionResult.displayName =
    "proto.whitelabelairportrpc.ExtensionActionResult";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.whitelabelairportrpc.ExtensionList = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.whitelabelairportrpc.ExtensionList.repeatedFields_,
    null
  );
};
goog.inherits(proto.whitelabelairportrpc.ExtensionList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.whitelabelairportrpc.ExtensionList.displayName =
    "proto.whitelabelairportrpc.ExtensionList";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.whitelabelairportrpc.EditExtensionRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.whitelabelairportrpc.EditExtensionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.whitelabelairportrpc.EditExtensionRequest.displayName =
    "proto.whitelabelairportrpc.EditExtensionRequest";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.whitelabelairportrpc.Extension = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.whitelabelairportrpc.Extension, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.whitelabelairportrpc.Extension.displayName =
    "proto.whitelabelairportrpc.Extension";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.whitelabelairportrpc.ExtensionRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.whitelabelairportrpc.ExtensionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.whitelabelairportrpc.ExtensionRequest.displayName =
    "proto.whitelabelairportrpc.ExtensionRequest";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.whitelabelairportrpc.SendExtensionDataRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(
  proto.whitelabelairportrpc.SendExtensionDataRequest,
  jspb.Message
);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.whitelabelairportrpc.SendExtensionDataRequest.displayName =
    "proto.whitelabelairportrpc.SendExtensionDataRequest";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.whitelabelairportrpc.ExtensionResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.whitelabelairportrpc.ExtensionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.whitelabelairportrpc.ExtensionResponse.displayName =
    "proto.whitelabelairportrpc.ExtensionResponse";
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.whitelabelairportrpc.ExtensionActionResult.prototype.toObject =
    function (opt_includeInstance) {
      return proto.whitelabelairportrpc.ExtensionActionResult.toObject(
        opt_includeInstance,
        this
      );
    };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.whitelabelairportrpc.ExtensionActionResult} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.whitelabelairportrpc.ExtensionActionResult.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        extensionId: jspb.Message.getFieldWithDefault(msg, 1, ""),
        code: jspb.Message.getFieldWithDefault(msg, 2, 0),
        message: jspb.Message.getFieldWithDefault(msg, 3, ""),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.whitelabelairportrpc.ExtensionActionResult}
 */
proto.whitelabelairportrpc.ExtensionActionResult.deserializeBinary = function (
  bytes
) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.whitelabelairportrpc.ExtensionActionResult();
  return proto.whitelabelairportrpc.ExtensionActionResult.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.whitelabelairportrpc.ExtensionActionResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.whitelabelairportrpc.ExtensionActionResult}
 */
proto.whitelabelairportrpc.ExtensionActionResult.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
        case 1:
          var value = /** @type {string} */ (reader.readString());
          msg.setExtensionId(value);
          break;
        case 2:
          var value = /** @type {!proto.whitelabelairportrpc.ResponseCode} */ (
            reader.readEnum()
          );
          msg.setCode(value);
          break;
        case 3:
          var value = /** @type {string} */ (reader.readString());
          msg.setMessage(value);
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  };

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.whitelabelairportrpc.ExtensionActionResult.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.whitelabelairportrpc.ExtensionActionResult.serializeBinaryToWriter(
      this,
      writer
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.whitelabelairportrpc.ExtensionActionResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.whitelabelairportrpc.ExtensionActionResult.serializeBinaryToWriter =
  function (message, writer) {
    var f = undefined;
    f = message.getExtensionId();
    if (f.length > 0) {
      writer.writeString(1, f);
    }
    f = message.getCode();
    if (f !== 0.0) {
      writer.writeEnum(2, f);
    }
    f = message.getMessage();
    if (f.length > 0) {
      writer.writeString(3, f);
    }
  };

/**
 * optional string extension_id = 1;
 * @return {string}
 */
proto.whitelabelairportrpc.ExtensionActionResult.prototype.getExtensionId =
  function () {
    return /** @type {string} */ (
      jspb.Message.getFieldWithDefault(this, 1, "")
    );
  };

/**
 * @param {string} value
 * @return {!proto.whitelabelairportrpc.ExtensionActionResult} returns this
 */
proto.whitelabelairportrpc.ExtensionActionResult.prototype.setExtensionId =
  function (value) {
    return jspb.Message.setProto3StringField(this, 1, value);
  };

/**
 * optional ResponseCode code = 2;
 * @return {!proto.whitelabelairportrpc.ResponseCode}
 */
proto.whitelabelairportrpc.ExtensionActionResult.prototype.getCode =
  function () {
    return /** @type {!proto.whitelabelairportrpc.ResponseCode} */ (
      jspb.Message.getFieldWithDefault(this, 2, 0)
    );
  };

/**
 * @param {!proto.whitelabelairportrpc.ResponseCode} value
 * @return {!proto.whitelabelairportrpc.ExtensionActionResult} returns this
 */
proto.whitelabelairportrpc.ExtensionActionResult.prototype.setCode = function (
  value
) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};

/**
 * optional string message = 3;
 * @return {string}
 */
proto.whitelabelairportrpc.ExtensionActionResult.prototype.getMessage =
  function () {
    return /** @type {string} */ (
      jspb.Message.getFieldWithDefault(this, 3, "")
    );
  };

/**
 * @param {string} value
 * @return {!proto.whitelabelairportrpc.ExtensionActionResult} returns this
 */
proto.whitelabelairportrpc.ExtensionActionResult.prototype.setMessage =
  function (value) {
    return jspb.Message.setProto3StringField(this, 3, value);
  };

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.whitelabelairportrpc.ExtensionList.repeatedFields_ = [1];

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.whitelabelairportrpc.ExtensionList.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.whitelabelairportrpc.ExtensionList.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.whitelabelairportrpc.ExtensionList} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.whitelabelairportrpc.ExtensionList.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        extensionsList: jspb.Message.toObjectList(
          msg.getExtensionsList(),
          proto.whitelabelairportrpc.Extension.toObject,
          includeInstance
        ),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.whitelabelairportrpc.ExtensionList}
 */
proto.whitelabelairportrpc.ExtensionList.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.whitelabelairportrpc.ExtensionList();
  return proto.whitelabelairportrpc.ExtensionList.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.whitelabelairportrpc.ExtensionList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.whitelabelairportrpc.ExtensionList}
 */
proto.whitelabelairportrpc.ExtensionList.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
        case 1:
          var value = new proto.whitelabelairportrpc.Extension();
          reader.readMessage(
            value,
            proto.whitelabelairportrpc.Extension.deserializeBinaryFromReader
          );
          msg.addExtensions(value);
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  };

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.whitelabelairportrpc.ExtensionList.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.whitelabelairportrpc.ExtensionList.serializeBinaryToWriter(
      this,
      writer
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.whitelabelairportrpc.ExtensionList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.whitelabelairportrpc.ExtensionList.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getExtensionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.whitelabelairportrpc.Extension.serializeBinaryToWriter
    );
  }
};

/**
 * repeated Extension extensions = 1;
 * @return {!Array<!proto.whitelabelairportrpc.Extension>}
 */
proto.whitelabelairportrpc.ExtensionList.prototype.getExtensionsList =
  function () {
    return /** @type{!Array<!proto.whitelabelairportrpc.Extension>} */ (
      jspb.Message.getRepeatedWrapperField(
        this,
        proto.whitelabelairportrpc.Extension,
        1
      )
    );
  };

/**
 * @param {!Array<!proto.whitelabelairportrpc.Extension>} value
 * @return {!proto.whitelabelairportrpc.ExtensionList} returns this
 */
proto.whitelabelairportrpc.ExtensionList.prototype.setExtensionsList =
  function (value) {
    return jspb.Message.setRepeatedWrapperField(this, 1, value);
  };

/**
 * @param {!proto.whitelabelairportrpc.Extension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.whitelabelairportrpc.Extension}
 */
proto.whitelabelairportrpc.ExtensionList.prototype.addExtensions = function (
  opt_value,
  opt_index
) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    1,
    opt_value,
    proto.whitelabelairportrpc.Extension,
    opt_index
  );
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.whitelabelairportrpc.ExtensionList} returns this
 */
proto.whitelabelairportrpc.ExtensionList.prototype.clearExtensionsList =
  function () {
    return this.setExtensionsList([]);
  };

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.whitelabelairportrpc.EditExtensionRequest.prototype.toObject =
    function (opt_includeInstance) {
      return proto.whitelabelairportrpc.EditExtensionRequest.toObject(
        opt_includeInstance,
        this
      );
    };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.whitelabelairportrpc.EditExtensionRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.whitelabelairportrpc.EditExtensionRequest.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        extensionId: jspb.Message.getFieldWithDefault(msg, 1, ""),
        enable: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.whitelabelairportrpc.EditExtensionRequest}
 */
proto.whitelabelairportrpc.EditExtensionRequest.deserializeBinary = function (
  bytes
) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.whitelabelairportrpc.EditExtensionRequest();
  return proto.whitelabelairportrpc.EditExtensionRequest.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.whitelabelairportrpc.EditExtensionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.whitelabelairportrpc.EditExtensionRequest}
 */
proto.whitelabelairportrpc.EditExtensionRequest.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
        case 1:
          var value = /** @type {string} */ (reader.readString());
          msg.setExtensionId(value);
          break;
        case 2:
          var value = /** @type {boolean} */ (reader.readBool());
          msg.setEnable(value);
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  };

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.whitelabelairportrpc.EditExtensionRequest.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.whitelabelairportrpc.EditExtensionRequest.serializeBinaryToWriter(
      this,
      writer
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.whitelabelairportrpc.EditExtensionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.whitelabelairportrpc.EditExtensionRequest.serializeBinaryToWriter =
  function (message, writer) {
    var f = undefined;
    f = message.getExtensionId();
    if (f.length > 0) {
      writer.writeString(1, f);
    }
    f = message.getEnable();
    if (f) {
      writer.writeBool(2, f);
    }
  };

/**
 * optional string extension_id = 1;
 * @return {string}
 */
proto.whitelabelairportrpc.EditExtensionRequest.prototype.getExtensionId =
  function () {
    return /** @type {string} */ (
      jspb.Message.getFieldWithDefault(this, 1, "")
    );
  };

/**
 * @param {string} value
 * @return {!proto.whitelabelairportrpc.EditExtensionRequest} returns this
 */
proto.whitelabelairportrpc.EditExtensionRequest.prototype.setExtensionId =
  function (value) {
    return jspb.Message.setProto3StringField(this, 1, value);
  };

/**
 * optional bool enable = 2;
 * @return {boolean}
 */
proto.whitelabelairportrpc.EditExtensionRequest.prototype.getEnable =
  function () {
    return /** @type {boolean} */ (
      jspb.Message.getBooleanFieldWithDefault(this, 2, false)
    );
  };

/**
 * @param {boolean} value
 * @return {!proto.whitelabelairportrpc.EditExtensionRequest} returns this
 */
proto.whitelabelairportrpc.EditExtensionRequest.prototype.setEnable = function (
  value
) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.whitelabelairportrpc.Extension.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.whitelabelairportrpc.Extension.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.whitelabelairportrpc.Extension} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.whitelabelairportrpc.Extension.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        id: jspb.Message.getFieldWithDefault(msg, 1, ""),
        title: jspb.Message.getFieldWithDefault(msg, 2, ""),
        description: jspb.Message.getFieldWithDefault(msg, 3, ""),
        enable: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.whitelabelairportrpc.Extension}
 */
proto.whitelabelairportrpc.Extension.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.whitelabelairportrpc.Extension();
  return proto.whitelabelairportrpc.Extension.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.whitelabelairportrpc.Extension} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.whitelabelairportrpc.Extension}
 */
proto.whitelabelairportrpc.Extension.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setId(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setTitle(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.setDescription(value);
        break;
      case 4:
        var value = /** @type {boolean} */ (reader.readBool());
        msg.setEnable(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.whitelabelairportrpc.Extension.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.whitelabelairportrpc.Extension.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.whitelabelairportrpc.Extension} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.whitelabelairportrpc.Extension.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
  f = message.getEnable();
  if (f) {
    writer.writeBool(4, f);
  }
};

/**
 * optional string id = 1;
 * @return {string}
 */
proto.whitelabelairportrpc.Extension.prototype.getId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/**
 * @param {string} value
 * @return {!proto.whitelabelairportrpc.Extension} returns this
 */
proto.whitelabelairportrpc.Extension.prototype.setId = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string title = 2;
 * @return {string}
 */
proto.whitelabelairportrpc.Extension.prototype.getTitle = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};

/**
 * @param {string} value
 * @return {!proto.whitelabelairportrpc.Extension} returns this
 */
proto.whitelabelairportrpc.Extension.prototype.setTitle = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional string description = 3;
 * @return {string}
 */
proto.whitelabelairportrpc.Extension.prototype.getDescription = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};

/**
 * @param {string} value
 * @return {!proto.whitelabelairportrpc.Extension} returns this
 */
proto.whitelabelairportrpc.Extension.prototype.setDescription = function (
  value
) {
  return jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * optional bool enable = 4;
 * @return {boolean}
 */
proto.whitelabelairportrpc.Extension.prototype.getEnable = function () {
  return /** @type {boolean} */ (
    jspb.Message.getBooleanFieldWithDefault(this, 4, false)
  );
};

/**
 * @param {boolean} value
 * @return {!proto.whitelabelairportrpc.Extension} returns this
 */
proto.whitelabelairportrpc.Extension.prototype.setEnable = function (value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.whitelabelairportrpc.ExtensionRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.whitelabelairportrpc.ExtensionRequest.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.whitelabelairportrpc.ExtensionRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.whitelabelairportrpc.ExtensionRequest.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        extensionId: jspb.Message.getFieldWithDefault(msg, 1, ""),
        dataMap: (f = msg.getDataMap())
          ? f.toObject(includeInstance, undefined)
          : [],
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.whitelabelairportrpc.ExtensionRequest}
 */
proto.whitelabelairportrpc.ExtensionRequest.deserializeBinary = function (
  bytes
) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.whitelabelairportrpc.ExtensionRequest();
  return proto.whitelabelairportrpc.ExtensionRequest.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.whitelabelairportrpc.ExtensionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.whitelabelairportrpc.ExtensionRequest}
 */
proto.whitelabelairportrpc.ExtensionRequest.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
        case 1:
          var value = /** @type {string} */ (reader.readString());
          msg.setExtensionId(value);
          break;
        case 2:
          var value = msg.getDataMap();
          reader.readMessage(value, function (message, reader) {
            jspb.Map.deserializeBinary(
              message,
              reader,
              jspb.BinaryReader.prototype.readString,
              jspb.BinaryReader.prototype.readString,
              null,
              "",
              ""
            );
          });
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  };

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.whitelabelairportrpc.ExtensionRequest.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.whitelabelairportrpc.ExtensionRequest.serializeBinaryToWriter(
      this,
      writer
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.whitelabelairportrpc.ExtensionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.whitelabelairportrpc.ExtensionRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getExtensionId();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getDataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(
      2,
      writer,
      jspb.BinaryWriter.prototype.writeString,
      jspb.BinaryWriter.prototype.writeString
    );
  }
};

/**
 * optional string extension_id = 1;
 * @return {string}
 */
proto.whitelabelairportrpc.ExtensionRequest.prototype.getExtensionId =
  function () {
    return /** @type {string} */ (
      jspb.Message.getFieldWithDefault(this, 1, "")
    );
  };

/**
 * @param {string} value
 * @return {!proto.whitelabelairportrpc.ExtensionRequest} returns this
 */
proto.whitelabelairportrpc.ExtensionRequest.prototype.setExtensionId =
  function (value) {
    return jspb.Message.setProto3StringField(this, 1, value);
  };

/**
 * map<string, string> data = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.whitelabelairportrpc.ExtensionRequest.prototype.getDataMap = function (
  opt_noLazyCreate
) {
  return /** @type {!jspb.Map<string,string>} */ (
    jspb.Message.getMapField(this, 2, opt_noLazyCreate, null)
  );
};

/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.whitelabelairportrpc.ExtensionRequest} returns this
 */
proto.whitelabelairportrpc.ExtensionRequest.prototype.clearDataMap =
  function () {
    this.getDataMap().clear();
    return this;
  };

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.whitelabelairportrpc.SendExtensionDataRequest.prototype.toObject =
    function (opt_includeInstance) {
      return proto.whitelabelairportrpc.SendExtensionDataRequest.toObject(
        opt_includeInstance,
        this
      );
    };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.whitelabelairportrpc.SendExtensionDataRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.whitelabelairportrpc.SendExtensionDataRequest.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        extensionId: jspb.Message.getFieldWithDefault(msg, 1, ""),
        button: jspb.Message.getFieldWithDefault(msg, 2, ""),
        dataMap: (f = msg.getDataMap())
          ? f.toObject(includeInstance, undefined)
          : [],
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.whitelabelairportrpc.SendExtensionDataRequest}
 */
proto.whitelabelairportrpc.SendExtensionDataRequest.deserializeBinary =
  function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.whitelabelairportrpc.SendExtensionDataRequest();
    return proto.whitelabelairportrpc.SendExtensionDataRequest.deserializeBinaryFromReader(
      msg,
      reader
    );
  };

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.whitelabelairportrpc.SendExtensionDataRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.whitelabelairportrpc.SendExtensionDataRequest}
 */
proto.whitelabelairportrpc.SendExtensionDataRequest.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
        case 1:
          var value = /** @type {string} */ (reader.readString());
          msg.setExtensionId(value);
          break;
        case 2:
          var value = /** @type {string} */ (reader.readString());
          msg.setButton(value);
          break;
        case 3:
          var value = msg.getDataMap();
          reader.readMessage(value, function (message, reader) {
            jspb.Map.deserializeBinary(
              message,
              reader,
              jspb.BinaryReader.prototype.readString,
              jspb.BinaryReader.prototype.readString,
              null,
              "",
              ""
            );
          });
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  };

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.whitelabelairportrpc.SendExtensionDataRequest.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.whitelabelairportrpc.SendExtensionDataRequest.serializeBinaryToWriter(
      this,
      writer
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.whitelabelairportrpc.SendExtensionDataRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.whitelabelairportrpc.SendExtensionDataRequest.serializeBinaryToWriter =
  function (message, writer) {
    var f = undefined;
    f = message.getExtensionId();
    if (f.length > 0) {
      writer.writeString(1, f);
    }
    f = message.getButton();
    if (f.length > 0) {
      writer.writeString(2, f);
    }
    f = message.getDataMap(true);
    if (f && f.getLength() > 0) {
      f.serializeBinary(
        3,
        writer,
        jspb.BinaryWriter.prototype.writeString,
        jspb.BinaryWriter.prototype.writeString
      );
    }
  };

/**
 * optional string extension_id = 1;
 * @return {string}
 */
proto.whitelabelairportrpc.SendExtensionDataRequest.prototype.getExtensionId =
  function () {
    return /** @type {string} */ (
      jspb.Message.getFieldWithDefault(this, 1, "")
    );
  };

/**
 * @param {string} value
 * @return {!proto.whitelabelairportrpc.SendExtensionDataRequest} returns this
 */
proto.whitelabelairportrpc.SendExtensionDataRequest.prototype.setExtensionId =
  function (value) {
    return jspb.Message.setProto3StringField(this, 1, value);
  };

/**
 * optional string button = 2;
 * @return {string}
 */
proto.whitelabelairportrpc.SendExtensionDataRequest.prototype.getButton =
  function () {
    return /** @type {string} */ (
      jspb.Message.getFieldWithDefault(this, 2, "")
    );
  };

/**
 * @param {string} value
 * @return {!proto.whitelabelairportrpc.SendExtensionDataRequest} returns this
 */
proto.whitelabelairportrpc.SendExtensionDataRequest.prototype.setButton =
  function (value) {
    return jspb.Message.setProto3StringField(this, 2, value);
  };

/**
 * map<string, string> data = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.whitelabelairportrpc.SendExtensionDataRequest.prototype.getDataMap =
  function (opt_noLazyCreate) {
    return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate, null)
    );
  };

/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.whitelabelairportrpc.SendExtensionDataRequest} returns this
 */
proto.whitelabelairportrpc.SendExtensionDataRequest.prototype.clearDataMap =
  function () {
    this.getDataMap().clear();
    return this;
  };

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.whitelabelairportrpc.ExtensionResponse.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.whitelabelairportrpc.ExtensionResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.whitelabelairportrpc.ExtensionResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.whitelabelairportrpc.ExtensionResponse.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        type: jspb.Message.getFieldWithDefault(msg, 1, 0),
        extensionId: jspb.Message.getFieldWithDefault(msg, 2, ""),
        jsonUi: jspb.Message.getFieldWithDefault(msg, 3, ""),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.whitelabelairportrpc.ExtensionResponse}
 */
proto.whitelabelairportrpc.ExtensionResponse.deserializeBinary = function (
  bytes
) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.whitelabelairportrpc.ExtensionResponse();
  return proto.whitelabelairportrpc.ExtensionResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.whitelabelairportrpc.ExtensionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.whitelabelairportrpc.ExtensionResponse}
 */
proto.whitelabelairportrpc.ExtensionResponse.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
        case 1:
          var value =
            /** @type {!proto.whitelabelairportrpc.ExtensionResponseType} */ (
              reader.readEnum()
            );
          msg.setType(value);
          break;
        case 2:
          var value = /** @type {string} */ (reader.readString());
          msg.setExtensionId(value);
          break;
        case 3:
          var value = /** @type {string} */ (reader.readString());
          msg.setJsonUi(value);
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  };

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.whitelabelairportrpc.ExtensionResponse.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.whitelabelairportrpc.ExtensionResponse.serializeBinaryToWriter(
      this,
      writer
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.whitelabelairportrpc.ExtensionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.whitelabelairportrpc.ExtensionResponse.serializeBinaryToWriter =
  function (message, writer) {
    var f = undefined;
    f = message.getType();
    if (f !== 0.0) {
      writer.writeEnum(1, f);
    }
    f = message.getExtensionId();
    if (f.length > 0) {
      writer.writeString(2, f);
    }
    f = message.getJsonUi();
    if (f.length > 0) {
      writer.writeString(3, f);
    }
  };

/**
 * optional ExtensionResponseType type = 1;
 * @return {!proto.whitelabelairportrpc.ExtensionResponseType}
 */
proto.whitelabelairportrpc.ExtensionResponse.prototype.getType = function () {
  return /** @type {!proto.whitelabelairportrpc.ExtensionResponseType} */ (
    jspb.Message.getFieldWithDefault(this, 1, 0)
  );
};

/**
 * @param {!proto.whitelabelairportrpc.ExtensionResponseType} value
 * @return {!proto.whitelabelairportrpc.ExtensionResponse} returns this
 */
proto.whitelabelairportrpc.ExtensionResponse.prototype.setType = function (
  value
) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};

/**
 * optional string extension_id = 2;
 * @return {string}
 */
proto.whitelabelairportrpc.ExtensionResponse.prototype.getExtensionId =
  function () {
    return /** @type {string} */ (
      jspb.Message.getFieldWithDefault(this, 2, "")
    );
  };

/**
 * @param {string} value
 * @return {!proto.whitelabelairportrpc.ExtensionResponse} returns this
 */
proto.whitelabelairportrpc.ExtensionResponse.prototype.setExtensionId =
  function (value) {
    return jspb.Message.setProto3StringField(this, 2, value);
  };

/**
 * optional string json_ui = 3;
 * @return {string}
 */
proto.whitelabelairportrpc.ExtensionResponse.prototype.getJsonUi = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};

/**
 * @param {string} value
 * @return {!proto.whitelabelairportrpc.ExtensionResponse} returns this
 */
proto.whitelabelairportrpc.ExtensionResponse.prototype.setJsonUi = function (
  value
) {
  return jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * @enum {number}
 */
proto.whitelabelairportrpc.ExtensionResponseType = {
  NOTHING: 0,
  UPDATE_UI: 1,
  SHOW_DIALOG: 2,
  END: 3,
};

goog.object.extend(exports, proto.whitelabelairportrpc);
