/**
 * @fileoverview gRPC-Web generated client stub for whitelabelairportrpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.0
// source: whitelabelairport.proto

/* eslint-disable */
// @ts-nocheck

const grpc = {};
grpc.web = require("grpc-web");

var base_pb = require("./base_pb.js");
const proto = {};
proto.whitelabelairportrpc = require("./whitelabelairport_pb.js");

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.whitelabelairportrpc.HelloClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.whitelabelairportrpc.HelloPromiseClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.HelloRequest,
 *   !proto.whitelabelairportrpc.HelloResponse>}
 */
const methodDescriptor_Hello_SayHello = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.Hello/SayHello",
  grpc.web.MethodType.UNARY,
  base_pb.HelloRequest,
  base_pb.HelloResponse,
  /**
   * @param {!proto.whitelabelairportrpc.HelloRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  base_pb.HelloResponse.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.HelloResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.HelloResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.HelloClient.prototype.sayHello = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/whitelabelairportrpc.Hello/SayHello",
    request,
    metadata || {},
    methodDescriptor_Hello_SayHello,
    callback
  );
};

/**
 * @param {!proto.whitelabelairportrpc.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.HelloResponse>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.HelloPromiseClient.prototype.sayHello = function (
  request,
  metadata
) {
  return this.client_.unaryCall(
    this.hostname_ + "/whitelabelairportrpc.Hello/SayHello",
    request,
    metadata || {},
    methodDescriptor_Hello_SayHello
  );
};

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.whitelabelairportrpc.CoreClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.whitelabelairportrpc.CorePromiseClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.StartRequest,
 *   !proto.whitelabelairportrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_Start = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.Core/Start",
  grpc.web.MethodType.UNARY,
  proto.whitelabelairportrpc.StartRequest,
  proto.whitelabelairportrpc.CoreInfoResponse,
  /**
   * @param {!proto.whitelabelairportrpc.StartRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.CoreInfoResponse.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.start = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/whitelabelairportrpc.Core/Start",
    request,
    metadata || {},
    methodDescriptor_Core_Start,
    callback
  );
};

/**
 * @param {!proto.whitelabelairportrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.start = function (
  request,
  metadata
) {
  return this.client_.unaryCall(
    this.hostname_ + "/whitelabelairportrpc.Core/Start",
    request,
    metadata || {},
    methodDescriptor_Core_Start
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.Empty,
 *   !proto.whitelabelairportrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_CoreInfoListener = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.Core/CoreInfoListener",
  grpc.web.MethodType.SERVER_STREAMING,
  base_pb.Empty,
  proto.whitelabelairportrpc.CoreInfoResponse,
  /**
   * @param {!proto.whitelabelairportrpc.Empty} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.CoreInfoResponse.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.CoreInfoResponse>}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.coreInfoListener = function (
  request,
  metadata
) {
  return this.client_.serverStreaming(
    this.hostname_ + "/whitelabelairportrpc.Core/CoreInfoListener",
    request,
    metadata || {},
    methodDescriptor_Core_CoreInfoListener
  );
};

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.CoreInfoResponse>}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.coreInfoListener =
  function (request, metadata) {
    return this.client_.serverStreaming(
      this.hostname_ + "/whitelabelairportrpc.Core/CoreInfoListener",
      request,
      metadata || {},
      methodDescriptor_Core_CoreInfoListener
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.Empty,
 *   !proto.whitelabelairportrpc.OutboundGroupList>}
 */
const methodDescriptor_Core_OutboundsInfo = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.Core/OutboundsInfo",
  grpc.web.MethodType.SERVER_STREAMING,
  base_pb.Empty,
  proto.whitelabelairportrpc.OutboundGroupList,
  /**
   * @param {!proto.whitelabelairportrpc.Empty} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.OutboundGroupList.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.outboundsInfo = function (
  request,
  metadata
) {
  return this.client_.serverStreaming(
    this.hostname_ + "/whitelabelairportrpc.Core/OutboundsInfo",
    request,
    metadata || {},
    methodDescriptor_Core_OutboundsInfo
  );
};

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.outboundsInfo =
  function (request, metadata) {
    return this.client_.serverStreaming(
      this.hostname_ + "/whitelabelairportrpc.Core/OutboundsInfo",
      request,
      metadata || {},
      methodDescriptor_Core_OutboundsInfo
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.Empty,
 *   !proto.whitelabelairportrpc.OutboundGroupList>}
 */
const methodDescriptor_Core_MainOutboundsInfo = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.Core/MainOutboundsInfo",
  grpc.web.MethodType.SERVER_STREAMING,
  base_pb.Empty,
  proto.whitelabelairportrpc.OutboundGroupList,
  /**
   * @param {!proto.whitelabelairportrpc.Empty} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.OutboundGroupList.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.mainOutboundsInfo = function (
  request,
  metadata
) {
  return this.client_.serverStreaming(
    this.hostname_ + "/whitelabelairportrpc.Core/MainOutboundsInfo",
    request,
    metadata || {},
    methodDescriptor_Core_MainOutboundsInfo
  );
};

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.mainOutboundsInfo =
  function (request, metadata) {
    return this.client_.serverStreaming(
      this.hostname_ + "/whitelabelairportrpc.Core/MainOutboundsInfo",
      request,
      metadata || {},
      methodDescriptor_Core_MainOutboundsInfo
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.Empty,
 *   !proto.whitelabelairportrpc.SystemInfo>}
 */
const methodDescriptor_Core_GetSystemInfo = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.Core/GetSystemInfo",
  grpc.web.MethodType.SERVER_STREAMING,
  base_pb.Empty,
  proto.whitelabelairportrpc.SystemInfo,
  /**
   * @param {!proto.whitelabelairportrpc.Empty} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.SystemInfo.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.SystemInfo>}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.getSystemInfo = function (
  request,
  metadata
) {
  return this.client_.serverStreaming(
    this.hostname_ + "/whitelabelairportrpc.Core/GetSystemInfo",
    request,
    metadata || {},
    methodDescriptor_Core_GetSystemInfo
  );
};

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.SystemInfo>}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.getSystemInfo =
  function (request, metadata) {
    return this.client_.serverStreaming(
      this.hostname_ + "/whitelabelairportrpc.Core/GetSystemInfo",
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemInfo
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.SetupRequest,
 *   !proto.whitelabelairportrpc.Response>}
 */
const methodDescriptor_Core_Setup = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.Core/Setup",
  grpc.web.MethodType.UNARY,
  proto.whitelabelairportrpc.SetupRequest,
  proto.whitelabelairportrpc.Response,
  /**
   * @param {!proto.whitelabelairportrpc.SetupRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.Response.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.SetupRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.setup = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/whitelabelairportrpc.Core/Setup",
    request,
    metadata || {},
    methodDescriptor_Core_Setup,
    callback
  );
};

/**
 * @param {!proto.whitelabelairportrpc.SetupRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.Response>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.setup = function (
  request,
  metadata
) {
  return this.client_.unaryCall(
    this.hostname_ + "/whitelabelairportrpc.Core/Setup",
    request,
    metadata || {},
    methodDescriptor_Core_Setup
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.ParseRequest,
 *   !proto.whitelabelairportrpc.ParseResponse>}
 */
const methodDescriptor_Core_Parse = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.Core/Parse",
  grpc.web.MethodType.UNARY,
  proto.whitelabelairportrpc.ParseRequest,
  proto.whitelabelairportrpc.ParseResponse,
  /**
   * @param {!proto.whitelabelairportrpc.ParseRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.ParseResponse.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.ParseRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.ParseResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.ParseResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.parse = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/whitelabelairportrpc.Core/Parse",
    request,
    metadata || {},
    methodDescriptor_Core_Parse,
    callback
  );
};

/**
 * @param {!proto.whitelabelairportrpc.ParseRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.ParseResponse>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.parse = function (
  request,
  metadata
) {
  return this.client_.unaryCall(
    this.hostname_ + "/whitelabelairportrpc.Core/Parse",
    request,
    metadata || {},
    methodDescriptor_Core_Parse
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.ChangeWhiteLabelAirportSettingsRequest,
 *   !proto.whitelabelairportrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_ChangeWhiteLabelAirportSettings =
  new grpc.web.MethodDescriptor(
    "/whitelabelairportrpc.Core/ChangeWhiteLabelAirportSettings",
    grpc.web.MethodType.UNARY,
    proto.whitelabelairportrpc.ChangeWhiteLabelAirportSettingsRequest,
    proto.whitelabelairportrpc.CoreInfoResponse,
    /**
     * @param {!proto.whitelabelairportrpc.ChangeWhiteLabelAirportSettingsRequest} request
     * @return {!Uint8Array}
     */
    function (request) {
      return request.serializeBinary();
    },
    proto.whitelabelairportrpc.CoreInfoResponse.deserializeBinary
  );

/**
 * @param {!proto.whitelabelairportrpc.ChangeWhiteLabelAirportSettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.changeWhiteLabelAirportSettings =
  function (request, metadata, callback) {
    return this.client_.rpcCall(
      this.hostname_ +
        "/whitelabelairportrpc.Core/ChangeWhiteLabelAirportSettings",
      request,
      metadata || {},
      methodDescriptor_Core_ChangeWhiteLabelAirportSettings,
      callback
    );
  };

/**
 * @param {!proto.whitelabelairportrpc.ChangeWhiteLabelAirportSettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.changeWhiteLabelAirportSettings =
  function (request, metadata) {
    return this.client_.unaryCall(
      this.hostname_ +
        "/whitelabelairportrpc.Core/ChangeWhiteLabelAirportSettings",
      request,
      metadata || {},
      methodDescriptor_Core_ChangeWhiteLabelAirportSettings
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.StartRequest,
 *   !proto.whitelabelairportrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_StartService = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.Core/StartService",
  grpc.web.MethodType.UNARY,
  proto.whitelabelairportrpc.StartRequest,
  proto.whitelabelairportrpc.CoreInfoResponse,
  /**
   * @param {!proto.whitelabelairportrpc.StartRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.CoreInfoResponse.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.startService = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/whitelabelairportrpc.Core/StartService",
    request,
    metadata || {},
    methodDescriptor_Core_StartService,
    callback
  );
};

/**
 * @param {!proto.whitelabelairportrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.startService = function (
  request,
  metadata
) {
  return this.client_.unaryCall(
    this.hostname_ + "/whitelabelairportrpc.Core/StartService",
    request,
    metadata || {},
    methodDescriptor_Core_StartService
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.Empty,
 *   !proto.whitelabelairportrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_Stop = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.Core/Stop",
  grpc.web.MethodType.UNARY,
  base_pb.Empty,
  proto.whitelabelairportrpc.CoreInfoResponse,
  /**
   * @param {!proto.whitelabelairportrpc.Empty} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.CoreInfoResponse.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.stop = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/whitelabelairportrpc.Core/Stop",
    request,
    metadata || {},
    methodDescriptor_Core_Stop,
    callback
  );
};

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.stop = function (
  request,
  metadata
) {
  return this.client_.unaryCall(
    this.hostname_ + "/whitelabelairportrpc.Core/Stop",
    request,
    metadata || {},
    methodDescriptor_Core_Stop
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.StartRequest,
 *   !proto.whitelabelairportrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_Restart = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.Core/Restart",
  grpc.web.MethodType.UNARY,
  proto.whitelabelairportrpc.StartRequest,
  proto.whitelabelairportrpc.CoreInfoResponse,
  /**
   * @param {!proto.whitelabelairportrpc.StartRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.CoreInfoResponse.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.restart = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/whitelabelairportrpc.Core/Restart",
    request,
    metadata || {},
    methodDescriptor_Core_Restart,
    callback
  );
};

/**
 * @param {!proto.whitelabelairportrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.restart = function (
  request,
  metadata
) {
  return this.client_.unaryCall(
    this.hostname_ + "/whitelabelairportrpc.Core/Restart",
    request,
    metadata || {},
    methodDescriptor_Core_Restart
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.SelectOutboundRequest,
 *   !proto.whitelabelairportrpc.Response>}
 */
const methodDescriptor_Core_SelectOutbound = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.Core/SelectOutbound",
  grpc.web.MethodType.UNARY,
  proto.whitelabelairportrpc.SelectOutboundRequest,
  proto.whitelabelairportrpc.Response,
  /**
   * @param {!proto.whitelabelairportrpc.SelectOutboundRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.Response.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.SelectOutboundRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.selectOutbound = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/whitelabelairportrpc.Core/SelectOutbound",
    request,
    metadata || {},
    methodDescriptor_Core_SelectOutbound,
    callback
  );
};

/**
 * @param {!proto.whitelabelairportrpc.SelectOutboundRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.Response>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.selectOutbound =
  function (request, metadata) {
    return this.client_.unaryCall(
      this.hostname_ + "/whitelabelairportrpc.Core/SelectOutbound",
      request,
      metadata || {},
      methodDescriptor_Core_SelectOutbound
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.UrlTestRequest,
 *   !proto.whitelabelairportrpc.Response>}
 */
const methodDescriptor_Core_UrlTest = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.Core/UrlTest",
  grpc.web.MethodType.UNARY,
  proto.whitelabelairportrpc.UrlTestRequest,
  proto.whitelabelairportrpc.Response,
  /**
   * @param {!proto.whitelabelairportrpc.UrlTestRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.Response.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.UrlTestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.urlTest = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/whitelabelairportrpc.Core/UrlTest",
    request,
    metadata || {},
    methodDescriptor_Core_UrlTest,
    callback
  );
};

/**
 * @param {!proto.whitelabelairportrpc.UrlTestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.Response>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.urlTest = function (
  request,
  metadata
) {
  return this.client_.unaryCall(
    this.hostname_ + "/whitelabelairportrpc.Core/UrlTest",
    request,
    metadata || {},
    methodDescriptor_Core_UrlTest
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.GenerateWarpConfigRequest,
 *   !proto.whitelabelairportrpc.WarpGenerationResponse>}
 */
const methodDescriptor_Core_GenerateWarpConfig = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.Core/GenerateWarpConfig",
  grpc.web.MethodType.UNARY,
  proto.whitelabelairportrpc.GenerateWarpConfigRequest,
  proto.whitelabelairportrpc.WarpGenerationResponse,
  /**
   * @param {!proto.whitelabelairportrpc.GenerateWarpConfigRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.WarpGenerationResponse.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.GenerateWarpConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.WarpGenerationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.WarpGenerationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.generateWarpConfig = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/whitelabelairportrpc.Core/GenerateWarpConfig",
    request,
    metadata || {},
    methodDescriptor_Core_GenerateWarpConfig,
    callback
  );
};

/**
 * @param {!proto.whitelabelairportrpc.GenerateWarpConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.WarpGenerationResponse>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.generateWarpConfig =
  function (request, metadata) {
    return this.client_.unaryCall(
      this.hostname_ + "/whitelabelairportrpc.Core/GenerateWarpConfig",
      request,
      metadata || {},
      methodDescriptor_Core_GenerateWarpConfig
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.Empty,
 *   !proto.whitelabelairportrpc.SystemProxyStatus>}
 */
const methodDescriptor_Core_GetSystemProxyStatus =
  new grpc.web.MethodDescriptor(
    "/whitelabelairportrpc.Core/GetSystemProxyStatus",
    grpc.web.MethodType.UNARY,
    base_pb.Empty,
    proto.whitelabelairportrpc.SystemProxyStatus,
    /**
     * @param {!proto.whitelabelairportrpc.Empty} request
     * @return {!Uint8Array}
     */
    function (request) {
      return request.serializeBinary();
    },
    proto.whitelabelairportrpc.SystemProxyStatus.deserializeBinary
  );

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.SystemProxyStatus)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.SystemProxyStatus>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.getSystemProxyStatus =
  function (request, metadata, callback) {
    return this.client_.rpcCall(
      this.hostname_ + "/whitelabelairportrpc.Core/GetSystemProxyStatus",
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemProxyStatus,
      callback
    );
  };

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.SystemProxyStatus>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.getSystemProxyStatus =
  function (request, metadata) {
    return this.client_.unaryCall(
      this.hostname_ + "/whitelabelairportrpc.Core/GetSystemProxyStatus",
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemProxyStatus
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.SetSystemProxyEnabledRequest,
 *   !proto.whitelabelairportrpc.Response>}
 */
const methodDescriptor_Core_SetSystemProxyEnabled =
  new grpc.web.MethodDescriptor(
    "/whitelabelairportrpc.Core/SetSystemProxyEnabled",
    grpc.web.MethodType.UNARY,
    proto.whitelabelairportrpc.SetSystemProxyEnabledRequest,
    proto.whitelabelairportrpc.Response,
    /**
     * @param {!proto.whitelabelairportrpc.SetSystemProxyEnabledRequest} request
     * @return {!Uint8Array}
     */
    function (request) {
      return request.serializeBinary();
    },
    proto.whitelabelairportrpc.Response.deserializeBinary
  );

/**
 * @param {!proto.whitelabelairportrpc.SetSystemProxyEnabledRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.setSystemProxyEnabled =
  function (request, metadata, callback) {
    return this.client_.rpcCall(
      this.hostname_ + "/whitelabelairportrpc.Core/SetSystemProxyEnabled",
      request,
      metadata || {},
      methodDescriptor_Core_SetSystemProxyEnabled,
      callback
    );
  };

/**
 * @param {!proto.whitelabelairportrpc.SetSystemProxyEnabledRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.Response>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.setSystemProxyEnabled =
  function (request, metadata) {
    return this.client_.unaryCall(
      this.hostname_ + "/whitelabelairportrpc.Core/SetSystemProxyEnabled",
      request,
      metadata || {},
      methodDescriptor_Core_SetSystemProxyEnabled
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.Empty,
 *   !proto.whitelabelairportrpc.LogMessage>}
 */
const methodDescriptor_Core_LogListener = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.Core/LogListener",
  grpc.web.MethodType.SERVER_STREAMING,
  base_pb.Empty,
  proto.whitelabelairportrpc.LogMessage,
  /**
   * @param {!proto.whitelabelairportrpc.Empty} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.LogMessage.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.LogMessage>}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CoreClient.prototype.logListener = function (
  request,
  metadata
) {
  return this.client_.serverStreaming(
    this.hostname_ + "/whitelabelairportrpc.Core/LogListener",
    request,
    metadata || {},
    methodDescriptor_Core_LogListener
  );
};

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.LogMessage>}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.CorePromiseClient.prototype.logListener = function (
  request,
  metadata
) {
  return this.client_.serverStreaming(
    this.hostname_ + "/whitelabelairportrpc.Core/LogListener",
    request,
    metadata || {},
    methodDescriptor_Core_LogListener
  );
};

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.whitelabelairportrpc.TunnelServiceClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.whitelabelairportrpc.TunnelServicePromiseClient = function (
  hostname,
  credentials,
  options
) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.TunnelStartRequest,
 *   !proto.whitelabelairportrpc.TunnelResponse>}
 */
const methodDescriptor_TunnelService_Start = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.TunnelService/Start",
  grpc.web.MethodType.UNARY,
  proto.whitelabelairportrpc.TunnelStartRequest,
  proto.whitelabelairportrpc.TunnelResponse,
  /**
   * @param {!proto.whitelabelairportrpc.TunnelStartRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.TunnelResponse.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.TunnelStartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.TunnelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.TunnelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.TunnelServiceClient.prototype.start = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/whitelabelairportrpc.TunnelService/Start",
    request,
    metadata || {},
    methodDescriptor_TunnelService_Start,
    callback
  );
};

/**
 * @param {!proto.whitelabelairportrpc.TunnelStartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.TunnelResponse>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.TunnelServicePromiseClient.prototype.start =
  function (request, metadata) {
    return this.client_.unaryCall(
      this.hostname_ + "/whitelabelairportrpc.TunnelService/Start",
      request,
      metadata || {},
      methodDescriptor_TunnelService_Start
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.Empty,
 *   !proto.whitelabelairportrpc.TunnelResponse>}
 */
const methodDescriptor_TunnelService_Stop = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.TunnelService/Stop",
  grpc.web.MethodType.UNARY,
  base_pb.Empty,
  proto.whitelabelairportrpc.TunnelResponse,
  /**
   * @param {!proto.whitelabelairportrpc.Empty} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.TunnelResponse.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.TunnelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.TunnelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.TunnelServiceClient.prototype.stop = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/whitelabelairportrpc.TunnelService/Stop",
    request,
    metadata || {},
    methodDescriptor_TunnelService_Stop,
    callback
  );
};

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.TunnelResponse>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.TunnelServicePromiseClient.prototype.stop =
  function (request, metadata) {
    return this.client_.unaryCall(
      this.hostname_ + "/whitelabelairportrpc.TunnelService/Stop",
      request,
      metadata || {},
      methodDescriptor_TunnelService_Stop
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.Empty,
 *   !proto.whitelabelairportrpc.TunnelResponse>}
 */
const methodDescriptor_TunnelService_Status = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.TunnelService/Status",
  grpc.web.MethodType.UNARY,
  base_pb.Empty,
  proto.whitelabelairportrpc.TunnelResponse,
  /**
   * @param {!proto.whitelabelairportrpc.Empty} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.TunnelResponse.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.TunnelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.TunnelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.TunnelServiceClient.prototype.status = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/whitelabelairportrpc.TunnelService/Status",
    request,
    metadata || {},
    methodDescriptor_TunnelService_Status,
    callback
  );
};

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.TunnelResponse>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.TunnelServicePromiseClient.prototype.status =
  function (request, metadata) {
    return this.client_.unaryCall(
      this.hostname_ + "/whitelabelairportrpc.TunnelService/Status",
      request,
      metadata || {},
      methodDescriptor_TunnelService_Status
    );
  };

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.whitelabelairportrpc.Empty,
 *   !proto.whitelabelairportrpc.TunnelResponse>}
 */
const methodDescriptor_TunnelService_Exit = new grpc.web.MethodDescriptor(
  "/whitelabelairportrpc.TunnelService/Exit",
  grpc.web.MethodType.UNARY,
  base_pb.Empty,
  proto.whitelabelairportrpc.TunnelResponse,
  /**
   * @param {!proto.whitelabelairportrpc.Empty} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.whitelabelairportrpc.TunnelResponse.deserializeBinary
);

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.whitelabelairportrpc.TunnelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.whitelabelairportrpc.TunnelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.whitelabelairportrpc.TunnelServiceClient.prototype.exit = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/whitelabelairportrpc.TunnelService/Exit",
    request,
    metadata || {},
    methodDescriptor_TunnelService_Exit,
    callback
  );
};

/**
 * @param {!proto.whitelabelairportrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.whitelabelairportrpc.TunnelResponse>}
 *     Promise that resolves to the response
 */
proto.whitelabelairportrpc.TunnelServicePromiseClient.prototype.exit =
  function (request, metadata) {
    return this.client_.unaryCall(
      this.hostname_ + "/whitelabelairportrpc.TunnelService/Exit",
      request,
      metadata || {},
      methodDescriptor_TunnelService_Exit
    );
  };

module.exports = proto.whitelabelairportrpc;
